<a href="https://colab.research.google.com/github/rakesh723772/python-lab/blob/main/3_0289.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,3,0],float)
print(a>2)


[False  True False]


In [ ]:
import numpy as np
a=np.array([2,3,4])
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
b=np.array((2,3,4))
print(type(b))

<class 'numpy.ndarray'>


In [ ]:
a=np.array([[1,3,5],[2,4,6],[6,5,3]])
print(a[0][0])

1


In [ ]:
arr=np.zeros((3,3),int)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
arr=np.empty((3,4))
print(arr)

[[4.90337349e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [ ]:
arr=np.arange(10,30,5)
print(arr)

[10 15 20 25]


In [ ]:
arr=np.arange(0,2,0.3)
print(arr)

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [ ]:
arr=np.linspace(0,2,9)
print(arr)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [ ]:
arr=np.identity(3,int)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


program-01create a numpy array with 6 random integers from 10 to 30.

In [ ]:
arr=np.random.randint(10,31,6)
print(arr)

[25 14 19 26 15 20]


In [ ]:
def quicksort(arr):
  if len(arr) <=1:
    return arr
  pivot = arr[len(arr) // 2]
  left = [x for x in arr if x < pivot]
  middle = [x for x in arr if x == pivot]
  right = [x for x in arr if x > pivot]
  return quicksort(left) + middle + quicksort(right)

print(quicksort([3,6,8,10,1,2,1]))


[1, 1, 2, 3, 6, 8, 10]


In [ ]:
x = 'Rakesh'
print(x,type(x))


Rakesh <class 'str'>
